name: CI Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'front/**'
      - '.github/workflows/github-actions-front.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'front/**'
      - '.github/workflows/github-actions-front.yml'

permissions:
  contents: read
  checks: write

jobs:
  build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['22.x']
        os: [ubuntu-latest]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 0
    
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
  
    - name: npm install, build and test
      working-directory: ./front
      run: |
        npm install
        npm run build --if-present
        npm run test-coverage

    - name: Create test report
      uses: dorny/test-reporter@v1
      with:
        name: Karma Jasmine Tests
        path: front/coverage/bobapp/junit-report.xml
        reporter: java-junit

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v4
      with:
        files: front/coverage/bobapp/lcov.info
        token: ${{ secrets.CODECOV_TOKEN }}
    
    - name: Upload Karma coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: karma-report
        path: front/coverage/bobapp
    
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: front
        args: >
            -Dsonar.projectKey=morgan_Gerez-un-projet-collaboratif-en-integrant-une-demarche-CI-CD-front
            -Dsonar.organization=morgan
            -Dsonar.sources=src
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#QEMU : conteneur docker fonctionnant sur VM x86 and x64
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
#utilisation de dockerbuildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
#Login avec user docker et token généré sur dockerhub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#Build et push vers docker
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: ./front
          file: front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest
