name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths:
      - 'back/**'
      - '.github/workflows/github-actions-back.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'back/**'
      - '.github/workflows/github-actions-back.yml'

permissions:
  contents: read
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    
    - name: Set up JDK 11
      uses: actions/setup-java@v5.0.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      working-directory: ./back
      run: mvn -B package --file pom.xml

    - name: Test with Maven
      working-directory: ./back
      run: mvn clean test jacoco:report

    - name: Upload test report summary
      uses: phoenix-actions/test-reporting@v15
      with:
          name: Junit Tests
          path: back/target/surefire-reports/*.xml
          reporter: java-junit

    - name: Upload JaCoCo coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: back/target/site/jacoco/

    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build and analyze
      working-directory: ./back
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=morgan_MorganFerreira_Gerez-un-projet-collaboratif-en-integrant-une-demarche-CI-CD-back

#QEMU : conteneur docker fonctionnant sur VM x86 and x64
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
#utilisation de dockerbuildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
#Login avec user docker et token généré sur dockerhub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#Build et push vers docker
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: ./back
          file: back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:latest
